
use_frameworks!
platform :ios, '9.0'

target 'DGDownloadManager' do
  
	#pod 'DGDownloadManager/DGBackgroudDownloadManagers', :path => '../'
  pod 'DGDownloadManager',:subspecs => ['DGBackgroudDownloadManagers','DGDownloadManagers'], :path => '../'

end
